assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: RS01SBPS-PC01A-04C-IP3
stream:
  method: streamed
  name: primary_node_out_of_band_port_data
workflow_config:
  schedule: 0 0 * * *
